# -*- coding: utf-8 -*-
"""Mental_Health_EDA_Charts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PaC_LUxTjpIvio3d6yytEv-YUkB-rmy4

## 🔹 Import Libraries
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

sns.set(style='whitegrid')

"""## 🔹 Load Dataset"""

df = pd.read_csv('/content/cleaned_mental_health_survey.csv')  # Upload the CSV file in Colab first
df.head()

"""## 🔹 Dataset Overview"""

print("Shape:", df.shape)
df.info()
df.isnull().sum()
df.duplicated().sum()

"""## 🔹 Describe Dataset & Unique Values"""

df.describe(include='all')
for col in df.columns:
    print(f"{col}: {df[col].nunique()} unique values")

"""## 📊 Chart 1: Gender vs Treatment"""

plt.figure(figsize=(8,5))
sns.countplot(data=df, x='Gender', hue='treatment', palette='Set2')
plt.title('Gender vs Mental Health Treatment')
plt.xlabel('Gender')
plt.ylabel('Number of Respondents')
plt.legend(title='Sought Treatment')
plt.tight_layout()
plt.show()

"""## 📊 Chart 2: Family History vs Treatment"""

plt.figure(figsize=(7,5))
sns.countplot(data=df, x='family_history', hue='treatment', palette='Set1')
plt.title('Family History vs Mental Health Treatment')
plt.xlabel('Family History')
plt.ylabel('Number of Respondents')
plt.legend(title='Sought Treatment')
plt.tight_layout()
plt.show()

"""## 📊 Chart 3: Remote Work vs Work Interference"""

plt.figure(figsize=(8,5))
sns.countplot(data=df, x='remote_work', hue='work_interfere', palette='Pastel1')
plt.title('Remote Work vs Work Interference')
plt.xlabel('Remote Work')
plt.ylabel('Number of Respondents')
plt.legend(title='Work Interference', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""## 📊 Chart 4: Company Size vs Mental Health Benefits"""

plt.figure(figsize=(10,5))
sns.countplot(data=df, x='no_employees', hue='benefits', palette='Set3')
plt.title('Company Size vs Mental Health Benefits')
plt.xlabel('Company Size')
plt.ylabel('Number of Respondents')
plt.xticks(rotation=45)
plt.legend(title='Benefits')
plt.tight_layout()
plt.show()

"""## 📊 Chart 5: Work Interfere vs Treatment"""

plt.figure(figsize=(8,5))
sns.countplot(data=df, x='work_interfere', hue='treatment', palette='Set2')
plt.title('Work Interference vs Treatment')
plt.xlabel('Work Interference')
plt.ylabel('Number of Respondents')
plt.legend(title='Sought Treatment')
plt.tight_layout()
plt.show()

"""## 📊 Chart 6: Mental Health Consequence vs Supervisor Discussion"""

plt.figure(figsize=(8,5))
sns.countplot(data=df, x='mental_health_consequence', hue='supervisor', palette='coolwarm')
plt.title('Fear of Consequence vs Supervisor Discussion')
plt.xlabel('Fear of Consequence')
plt.ylabel('Number of Respondents')
plt.legend(title='Discuss with Supervisor')
plt.tight_layout()
plt.show()

"""## 📊 Chart 7:  Country vs Mental Health Treatment"""

# Top 10 countries
top_countries = df['Country'].value_counts().head(10).index

# Filter & plot
plt.figure(figsize=(12,6))
sns.countplot(data=df[df['Country'].isin(top_countries)], x='Country', hue='treatment', palette='Set2')
plt.title("Top 10 Countries vs Mental Health Treatment")
plt.xlabel("Country")
plt.ylabel("Number of Respondents")
plt.xticks(rotation=45)
plt.legend(title="Sought Treatment")
plt.tight_layout()
plt.show()

"""## 📊 Chart 14:Correlation Heatmap - Predictors of Treatment"""

import seaborn as sns
import matplotlib.pyplot as plt

# Encode relevant cols
df_encoded = df.copy()
df_encoded['treatment'] = df_encoded['treatment'].map({'Yes':1, 'No':0})
df_encoded['family_history'] = df_encoded['family_history'].map({'Yes':1, 'No':0})
df_encoded['work_interfere'] = df_encoded['work_interfere'].map({'Never':0, 'Rarely':1, 'Sometimes':2, 'Often':3})

# Correlation heatmap
plt.figure(figsize=(8,5))
sns.heatmap(df_encoded[['treatment', 'family_history', 'work_interfere']].corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap: Predictors vs Treatment")
plt.show()